### ISSUE TITLE
Relis les consignes stp

### ISSUE THREAD

**Issue by davidmarsprof** [Yvain16-69/PONG#1]
Allez Yvain, un petit effort relis les consignes stp...

**Comment by Yvain16-69** [comment]
J'ai de mon côté un code fonctionnelle, où est le problème ?

Le ven. 6 nov. 2020 à 15:55, davidmarsprof <notifications@github.com> a
écrit :

**Comment by davidmarsprof** [comment]
dommage, le terrain est pas centré, sinon c'est très bien.
